### ISSUE TITLE
[Feature Request]: Button tooltip when focus-visible

### ISSUE THREAD

**Issue by heybran** [Matsuuu/web-component-devtools#62]
### **Which browser are you using?**
Chrome

### **Is your feature request related to a problem? Please describe.**

Hi @Matsuuu, I was checking the React Developer Tools today, and I noticed when tab into the button, it has a tooltip displayed, which I think it'd be great for WCDT to implement that as well, to improve the accessibility.
<img width="728" alt="Screenshot 2023-06-22 at 19 40 03" src="https://github.com/Matsuuu/web-component-devtools/assets/75633537/d2a08b49-7f41-4520-8398-0b279e8b03ac">

### **Describe the solution you'd like**

So I played a bit with CSS -- locally only at the moment -- and this is what I come up with 2 ideas in terms of CSS codes.

#### 1) A hardcoded content on `::after` element. 
```css
.tag-show-button:focus-visible::after {
    position: absolute;
    content: 'Toggle tag';
    padding: .2rem .6rem;
    background: var(--paragraph-color);
    color: #fff;
    border-radius: 4px;
    top: calc(100% + 8px);
    left: 50%;
    transform: translateX(-50%);
    width: max-content;
}
```

And this is what it looks like in dev tool:

<img width="728" alt="Screenshot 2023-06-22 at 19 38 38" src="https://github.com/Matsuuu/web-component-devtools/assets/75633537/6fa9d0e2-8aaf-416b-b932-7310d5539d0c">

#### 2) Grab button title using `attr()`

```css
.tag-show-button:focus-visible::after {
    position: absolute;
    /* grab title from button title attribute */
    content: attr(title);
    padding: .2rem .6rem;
    background: var(--paragraph-color);
    color: #fff;
    border-radius: 4px;
    top: calc(100% + 8px);
    left: 50%;
    transform: translateX(-50%);
    width: max-content;
}
```
And this is what it looks like (will adjust the styles if we're going with this solution):

<img width="728" alt="Screenshot 2023-06-22 at 19 39 32" src="https://github.com/Matsuuu/web-component-devtools/assets/75633537/e23c61fb-0a77-4fbc-b756-7d35cd070105">

### **Questions** 

Would you like me to keep work on this so I can come back next time with a PR. Also, If I missed anything, please let me know.

Brandon
